version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet_api
    depends_on:
      - db
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=walletdb;Username=postgres;Password=postgres
    networks:
      - wallet-network
  db:
    image: postgres:15
    container_name: wallet_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: walletdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wallet-network

volumes:
  postgres_data:

networks:
  wallet-network:
